services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
      
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_no_sql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projet_nosql
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  postgres_data:
  mongo_data:
